/**
 * @file dev_conf.c
 * @brief Device Configuration Implementation for AMG8833
 * @date March 21, 2025
 *
 * Implementation of configuration functions for the AMG8833 thermal camera
 */

#include "dev_conf.h"
#include "main.h"

/**
 * Note: This file primarily contains configuration constants which are
 * defined in the header file. Most STM32 projects using HAL will already
 * have the I2C handle defined in i2c.c/h generated by CubeMX.
 *
 * This implementation file may be extended with additional configuration
 * functions as needed by the application.
 */

/**
 * @brief Configure the I2C interface for the AMG8833
 *
 * This function should be called if custom I2C configuration
 * beyond what's provided by CubeMX is required.
 *
 * @return HAL_OK if successful, HAL_ERROR otherwise
 */
HAL_StatusTypeDef AMG8833_ConfigureI2C(void)
{
    // Most STM32 projects will have I2C initialization handled by CubeMX
    // generated code (MX_I2C2_Init). If additional configuration is needed,
    // it can be implemented here.

    // Example: Change I2C timing if needed
    /*
    hi2c2.Instance = I2C2;
    hi2c2.Init.Timing = 0x10909CEC;
    hi2c2.Init.OwnAddress1 = 0;
    hi2c2.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
    hi2c2.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c2.Init.OwnAddress2 = 0;
    hi2c2.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
    hi2c2.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c2.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;

    if (HAL_I2C_Init(&hi2c2) != HAL_OK) {
        return HAL_ERROR;
    }

    // Configure Analog filter
    if (HAL_I2CEx_ConfigAnalogFilter(&hi2c2, I2C_ANALOGFILTER_ENABLE) != HAL_OK) {
        return HAL_ERROR;
    }

    // Configure Digital filter
    if (HAL_I2CEx_ConfigDigitalFilter(&hi2c2, 0) != HAL_OK) {
        return HAL_ERROR;
    }
    */

    return HAL_OK;
}

/**
 * @brief Adjust AMG8833 configuration based on application requirements
 *
 * This function can be used to change settings like frame rate or
 * power mode based on specific application needs.
 *
 * @param frameRate Frame rate setting (AMG8833_FPS_10 or AMG8833_FPS_1)
 * @return HAL_OK if successful, HAL_ERROR otherwise
 */
HAL_StatusTypeDef AMG8833_AdjustConfig(uint8_t frameRate)
{
    HAL_StatusTypeDef status;

    // Set the frame rate
    status = HAL_I2C_Mem_Write(&AMG8833_I2C, AMG8833_ADDR, AMG8833_FPSC,
                              I2C_MEMADD_SIZE_8BIT, &frameRate, 1, AMG8833_I2C_TIMEOUT);

    return status;
}

/**
 * @brief Enable interrupt functionality on the AMG8833
 *
 * @param interruptMode Interrupt mode to set
 * @param upperLimit Upper temperature limit for interrupt
 * @param lowerLimit Lower temperature limit for interrupt
 * @param hysteresis Hysteresis value for interrupt
 * @return HAL_OK if successful, HAL_ERROR otherwise
 */
HAL_StatusTypeDef AMG8833_ConfigureInterrupt(uint8_t interruptMode,
                                           float upperLimit,
                                           float lowerLimit,
                                           float hysteresis)
{
    HAL_StatusTypeDef status;

    // Convert temperature values to raw register values
    int16_t upperRaw = (int16_t)(upperLimit / AMG8833_TEMP_FACTOR);
    int16_t lowerRaw = (int16_t)(lowerLimit / AMG8833_TEMP_FACTOR);
    int16_t hystRaw = (int16_t)(hysteresis / AMG8833_TEMP_FACTOR);

    // Prepare data bytes
    uint8_t upperBytes[2] = {upperRaw & 0xFF, (upperRaw >> 8) & 0xFF};
    uint8_t lowerBytes[2] = {lowerRaw & 0xFF, (lowerRaw >> 8) & 0xFF};
    uint8_t hystBytes[2] = {hystRaw & 0xFF, (hystRaw >> 8) & 0xFF};

    // Set interrupt mode
    status = HAL_I2C_Mem_Write(&AMG8833_I2C, AMG8833_ADDR, AMG8833_INT_CTRL,
                              I2C_MEMADD_SIZE_8BIT, &interruptMode, 1, AMG8833_I2C_TIMEOUT);
    if (status != HAL_OK) {
        return status;
    }

    // Set upper limit
    status = HAL_I2C_Mem_Write(&AMG8833_I2C, AMG8833_ADDR, AMG8833_INT_LEVEL_UPPER,
                              I2C_MEMADD_SIZE_8BIT, upperBytes, 2, AMG8833_I2C_TIMEOUT);
    if (status != HAL_OK) {
        return status;
    }

    // Set lower limit
    status = HAL_I2C_Mem_Write(&AMG8833_I2C, AMG8833_ADDR, AMG8833_INT_LEVEL_LOWER,
                              I2C_MEMADD_SIZE_8BIT, lowerBytes, 2, AMG8833_I2C_TIMEOUT);
    if (status != HAL_OK) {
        return status;
    }

    // Set hysteresis
    status = HAL_I2C_Mem_Write(&AMG8833_I2C, AMG8833_ADDR, AMG8833_INT_LEVEL_HYST,
                              I2C_MEMADD_SIZE_8BIT, hystBytes, 2, AMG8833_I2C_TIMEOUT);

    return status;
}
